name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.0
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec spec
